# Example configuration file for gosqlpp MCP Proxy
# Copy this file to config.yaml and modify as needed

# Transport mode: "stdio" or "http"
transport: stdio

# Port to listen on (HTTP mode only)
port: 8099

# Port where the sqlpp MCP server is running (HTTP mode only)
xfer-port: 8891

# Path to the mcp_sqlpp executable
exe-path: ./mcp_sqlpp

# Additional configuration options can be added here as the project evolves
